language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - PANDAS_VERSION=v0.13.1
  - PANDAS_VERSION=v0.14.1
  - PANDAS_VERSION=master

before_install:
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get -qq remove postgis
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  #- sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
  #- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get install gdal-bin libgdal-dev libgdal1 libspatialindex-dev libspatialindex1 
#  - sudo -u postgres psql -c "drop database if exists test_geopandas"
#  - sudo -u postgres psql -c "create database test_geopandas"
#  - sudo -u postgres psql -c "create extension postgis" -d test_geopandas

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements.test.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r .requirements-2.6.txt --use-mirrors; fi
  - git clone git://github.com/pydata/pandas.git
  - cd pandas
  - git checkout $PANDAS_VERSION
  - python setup.py install
  - cd ..

script:
  - py.test tests --cov geopandas -v --cov-report term-missing

after_success:
  - coveralls
